"""
FasalDoc Treatment & Disease Seed Script
Data sourced from:
- ICAR-NCIPM: ncipm.icar.gov.in
- NIPHM IPM Packages: niphm.gov.in
- ICAR-IIWBR Karnal (wheat)
- ICAR-IIRR Hyderabad (rice)
- ICAR-IIHR Bengaluru (vegetables)
- ICAR-CPRI Shimla (potato)
- PAU Ludhiana (Punjab crops)
- CIB&RC registered pesticides: cibrc.nic.in
"""

import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.db.session import SessionLocal
from app.models.disease import Disease
from app.models.treatment import Treatment

def seed():
    db = SessionLocal()
    try:
        # Clear existing data
        db.query(Treatment).delete()
        db.query(Disease).delete()
        db.commit()
        print("Cleared existing data.")

        # ── DISEASES ──────────────────────────────────────────────
        diseases = [

            # ── WHEAT ──
            Disease(
                id="wheat_yellow_rust",
                class_index=0,
                name_en="Yellow Rust (Stripe Rust)",
                name_hi="पीला रतुआ (धारीदार रस्ट)",
                name_pa="ਪੀਲਾ ਕੁੰਗੀ (ਧਾਰੀਦਾਰ ਰਸਟ)",
                crop_en="Wheat",
                crop_hi="गेहूं",
                crop_pa="ਕਣਕ",
                description_en="Caused by Puccinia striiformis. Yellow stripes appear on leaves parallel to leaf veins. High risk Nov–Feb in Punjab, Haryana, UP. Can cause 70% yield loss if untreated. Source: ICAR-IIWBR Karnal.",
                description_hi="पुक्सिनिया स्ट्रिफॉर्मिस से होती है। पत्तियों पर पीली धारियां दिखती हैं। नवंबर-फरवरी में पंजाब, हरियाणा में अधिक खतरा। स्रोत: ICAR-IIWBR करनाल।",
                description_pa="ਪੁਕਸੀਨੀਆ ਸਟ੍ਰਾਈਫਾਰਮਿਸ ਕਾਰਨ ਹੁੰਦਾ ਹੈ। ਪੱਤਿਆਂ 'ਤੇ ਪੀਲੀਆਂ ਧਾਰੀਆਂ ਦਿਖਦੀਆਂ ਹਨ। ਸਰੋਤ: ICAR-IIWBR ਕਰਨਾਲ।",
                severity="high",
            ),
            Disease(
                id="wheat_brown_rust",
                class_index=1,
                name_en="Brown Rust (Leaf Rust)",
                name_hi="भूरा रतुआ (पत्ती रस्ट)",
                name_pa="ਭੂਰਾ ਕੁੰਗੀ (ਪੱਤਾ ਰਸਟ)",
                crop_en="Wheat",
                crop_hi="गेहूं",
                crop_pa="ਕਣਕ",
                description_en="Caused by Puccinia triticina. Orange-brown pustules on leaf surface. Emerges at boot stage. Source: PAU Ludhiana & ICAR-IIWBR Karnal.",
                description_hi="पुक्सिनिया ट्रिटिसीना से। पत्ती पर नारंगी-भूरे फफोले। स्रोत: PAU लुधियाना।",
                description_pa="ਪੁਕਸੀਨੀਆ ਟ੍ਰਿਟਿਸੀਨਾ ਕਾਰਨ। ਪੱਤੇ 'ਤੇ ਸੰਤਰੀ-ਭੂਰੇ ਫੋੜੇ। ਸਰੋਤ: PAU ਲੁਧਿਆਣਾ।",
                severity="medium",
            ),
            Disease(
                id="wheat_karnal_bunt",
                class_index=2,
                name_en="Karnal Bunt",
                name_hi="करनाल बंट",
                name_pa="ਕਰਨਾਲ ਬੰਟ",
                crop_en="Wheat",
                crop_hi="गेहूं",
                crop_pa="ਕਣਕ",
                description_en="Caused by Tilletia indica. Partial bunting of wheat grains with fishy smell. Notifiable disease — report to state agriculture dept. Source: ICAR-IIWBR Karnal.",
                description_hi="टिलेटिया इंडिका से। अनाज में मछली जैसी गंध। सूचना देने योग्य रोग। स्रोत: ICAR-IIWBR करनाल।",
                description_pa="ਟਿਲੇਟੀਆ ਇੰਡਿਕਾ ਕਾਰਨ। ਅਨਾਜ ਵਿੱਚ ਮੱਛੀ ਵਰਗੀ ਗੰਧ। ਸੂਚਨਾ ਯੋਗ ਬਿਮਾਰੀ। ਸਰੋਤ: ICAR-IIWBR ਕਰਨਾਲ।",
                severity="high",
            ),
            Disease(
                id="wheat_powdery_mildew",
                class_index=3,
                name_en="Powdery Mildew",
                name_hi="चूर्णिल आसिता",
                name_pa="ਪਾਊਡਰੀ ਮਿਲਡਿਊ",
                crop_en="Wheat",
                crop_hi="गेहूं",
                crop_pa="ਕਣਕ",
                description_en="Caused by Blumeria graminis. White powdery growth on upper leaf surface. Favoured by cool humid weather. Source: PAU Ludhiana & HAU Hisar.",
                description_hi="ब्लूमेरिया ग्रेमिनिस से। पत्ती पर सफेद पाउडर जैसी वृद्धि। स्रोत: PAU लुधियाना।",
                description_pa="ਬਲੂਮੇਰੀਆ ਗ੍ਰੈਮੀਨਿਸ ਕਾਰਨ। ਪੱਤੇ 'ਤੇ ਚਿੱਟਾ ਪਾਊਡਰ। ਸਰੋਤ: PAU ਲੁਧਿਆਣਾ।",
                severity="medium",
            ),

            # ── RICE ──
            Disease(
                id="rice_blast",
                class_index=4,
                name_en="Rice Blast",
                name_hi="धान का ब्लास्ट",
                name_pa="ਝੋਨੇ ਦਾ ਬਲਾਸਟ",
                crop_en="Rice",
                crop_hi="धान",
                crop_pa="ਝੋਨਾ",
                description_en="Caused by Magnaporthe oryzae. Diamond-shaped lesions on leaves. Can destroy entire crop at neck blast stage. High risk Jul–Sep Kharif. Note: Tricyclazole banned in India 2020. Source: ICAR-IIRR Hyderabad.",
                description_hi="मैग्नापोर्थे ओराइजे से। पत्तियों पर हीरे के आकार के धब्बे। स्रोत: ICAR-IIRR हैदराबाद।",
                description_pa="ਮੈਗਨਾਪੋਰਥੇ ਓਰਾਈਜ਼ੇ ਕਾਰਨ। ਪੱਤਿਆਂ 'ਤੇ ਹੀਰੇ ਦੇ ਆਕਾਰ ਦੇ ਧੱਬੇ। ਸਰੋਤ: ICAR-IIRR ਹੈਦਰਾਬਾਦ।",
                severity="high",
            ),
            Disease(
                id="rice_sheath_blight",
                class_index=5,
                name_en="Sheath Blight",
                name_hi="शीथ ब्लाइट",
                name_pa="ਸ਼ੀਥ ਬਲਾਈਟ",
                crop_en="Rice",
                crop_hi="धान",
                crop_pa="ਝੋਨਾ",
                description_en="Caused by Rhizoctonia solani. Oval lesions on leaf sheaths near waterline. Second most damaging rice disease after blast. Source: ICAR-IIRR Hyderabad multilocational trial.",
                description_hi="राइज़ोक्टोनिया सोलानी से। पानी की रेखा के पास पत्ती के आवरण पर धब्बे। स्रोत: ICAR-IIRR हैदराबाद।",
                description_pa="ਰਾਈਜ਼ੋਕਟੋਨੀਆ ਸੋਲਾਨੀ ਕਾਰਨ। ਪਾਣੀ ਦੀ ਲਾਈਨ ਕੋਲ ਪੱਤੇ ਦੇ ਮਿਆਨ 'ਤੇ ਧੱਬੇ। ਸਰੋਤ: ICAR-IIRR।",
                severity="high",
            ),
            Disease(
                id="rice_bacterial_leaf_blight",
                class_index=6,
                name_en="Bacterial Leaf Blight (BLB)",
                name_hi="बैक्टीरियल लीफ ब्लाइट",
                name_pa="ਬੈਕਟੀਰੀਅਲ ਲੀਫ ਬਲਾਈਟ",
                crop_en="Rice",
                crop_hi="धान",
                crop_pa="ਝੋਨਾ",
                description_en="Caused by Xanthomonas oryzae. Yellowing from leaf tips, water-soaked margins. Causes 20% yield loss. Source: ICAR-NRRI Cuttack.",
                description_hi="ज़ैंथोमोनस ओराइजे से। पत्ती की नोक से पीलापन। स्रोत: ICAR-NRRI कटक।",
                description_pa="ਜ਼ੈਂਥੋਮੋਨਸ ਓਰਾਈਜ਼ੇ ਕਾਰਨ। ਪੱਤੀ ਦੀ ਨੋਕ ਤੋਂ ਪੀਲਾਪਣ। ਸਰੋਤ: ICAR-NRRI ਕਟਕ।",
                severity="high",
            ),
            Disease(
                id="rice_brown_spot",
                class_index=7,
                name_en="Brown Spot",
                name_hi="भूरा धब्बा रोग",
                name_pa="ਭੂਰੇ ਧੱਬੇ ਦੀ ਬਿਮਾਰੀ",
                crop_en="Rice",
                crop_hi="धान",
                crop_pa="ਝੋਨਾ",
                description_en="Caused by Helminthosporium oryzae. Oval brown spots with yellow halo. Worsened by potassium deficiency. Source: ICAR-NRRI Cuttack & ICAR-IIRR Hyderabad.",
                description_hi="हेल्मिंथोस्पोरियम ओराइजे से। पीले घेरे के साथ भूरे अंडाकार धब्बे। स्रोत: ICAR-NRRI कटक।",
                description_pa="ਹੈਲਮਿੰਥੋਸਪੋਰੀਅਮ ਓਰਾਈਜ਼ੇ ਕਾਰਨ। ਪੀਲੇ ਘੇਰੇ ਨਾਲ ਭੂਰੇ ਧੱਬੇ। ਸਰੋਤ: ICAR-NRRI ਕਟਕ।",
                severity="medium",
            ),

            # ── TOMATO ──
            Disease(
                id="tomato_early_blight",
                class_index=8,
                name_en="Early Blight",
                name_hi="अगेती झुलसन",
                name_pa="ਅਗੇਤੀ ਝੁਲਸਣ",
                crop_en="Tomato",
                crop_hi="टमाटर",
                crop_pa="ਟਮਾਟਰ",
                description_en="Caused by Alternaria solani. Dark brown concentric ring lesions on lower leaves. Favoured by warm humid conditions. Source: ICAR-IIHR Bengaluru & NCIPM.",
                description_hi="अल्टरनेरिया सोलानी से। निचली पत्तियों पर गहरे भूरे छल्लेदार धब्बे। स्रोत: ICAR-IIHR बेंगलुरु।",
                description_pa="ਅਲਟਰਨੇਰੀਆ ਸੋਲਾਨੀ ਕਾਰਨ। ਹੇਠਲੇ ਪੱਤਿਆਂ 'ਤੇ ਗੂੜ੍ਹੇ ਭੂਰੇ ਛੱਲੇਦਾਰ ਧੱਬੇ। ਸਰੋਤ: ICAR-IIHR।",
                severity="medium",
            ),
            Disease(
                id="tomato_late_blight",
                class_index=9,
                name_en="Late Blight",
                name_hi="पछेती झुलसन",
                name_pa="ਪਿਛੇਤੀ ਝੁਲਸਣ",
                crop_en="Tomato",
                crop_hi="टमाटर",
                crop_pa="ਟਮਾਟਰ",
                description_en="Caused by Phytophthora infestans. Water-soaked dark lesions, white mold on underside. Most destructive tomato disease. Act immediately. Source: ICAR-IIHR Bengaluru & NIPHM.",
                description_hi="फाइटोफ्थोरा इन्फेस्टांस से। पानी भरे काले धब्बे, नीचे सफेद फफूंद। तुरंत उपचार करें। स्रोत: ICAR-IIHR।",
                description_pa="ਫਾਈਟੋਫਥੋਰਾ ਇਨਫੈਸਟਾਂਸ ਕਾਰਨ। ਪਾਣੀ ਭਰੇ ਕਾਲੇ ਧੱਬੇ। ਤੁਰੰਤ ਇਲਾਜ ਕਰੋ। ਸਰੋਤ: ICAR-IIHR।",
                severity="high",
            ),
            Disease(
                id="tomato_leaf_mold",
                class_index=10,
                name_en="Leaf Mold",
                name_hi="पत्ती का फफूंद",
                name_pa="ਪੱਤੇ ਦਾ ਉੱਲੀ",
                crop_en="Tomato",
                crop_hi="टमाटर",
                crop_pa="ਟਮਾਟਰ",
                description_en="Caused by Passalora fulva. Yellow patches on upper leaf surface, olive-brown mold below. Common in polyhouses. Source: ICAR-IIHR Bengaluru.",
                description_hi="पासालोरा फुल्वा से। पत्ती के ऊपर पीले धब्बे, नीचे भूरी फफूंद। स्रोत: ICAR-IIHR।",
                description_pa="ਪਾਸਾਲੋਰਾ ਫੁਲਵਾ ਕਾਰਨ। ਪੱਤੇ ਦੇ ਉੱਪਰ ਪੀਲੇ ਧੱਬੇ। ਸਰੋਤ: ICAR-IIHR।",
                severity="medium",
            ),
            Disease(
                id="tomato_septoria_leaf_spot",
                class_index=11,
                name_en="Septoria Leaf Spot",
                name_hi="सेप्टोरिया पत्ती धब्बा",
                name_pa="ਸੈਪਟੋਰੀਆ ਪੱਤਾ ਧੱਬਾ",
                crop_en="Tomato",
                crop_hi="टमाटर",
                crop_pa="ਟਮਾਟਰ",
                description_en="Caused by Septoria lycopersici. Small circular spots with white centers and dark borders. Starts on lower leaves. Source: ICAR-IIHR Bengaluru & PAU Ludhiana.",
                description_hi="सेप्टोरिया लाइकोपर्सिसी से। सफेद केंद्र और काले किनारों वाले छोटे गोल धब्बे। स्रोत: ICAR-IIHR।",
                description_pa="ਸੈਪਟੋਰੀਆ ਲਾਈਕੋਪਰਸੀਸੀ ਕਾਰਨ। ਚਿੱਟੇ ਕੇਂਦਰ ਅਤੇ ਕਾਲੇ ਕਿਨਾਰਿਆਂ ਵਾਲੇ ਛੋਟੇ ਗੋਲ ਧੱਬੇ। ਸਰੋਤ: ICAR-IIHR।",
                severity="medium",
            ),
            Disease(
                id="tomato_spider_mites",
                class_index=12,
                name_en="Spider Mites (Two-spotted)",
                name_hi="मकड़ी के कण",
                name_pa="ਮੱਕੜੀ ਦੇ ਕੀੜੇ",
                crop_en="Tomato",
                crop_hi="टमाटर",
                crop_pa="ਟਮਾਟਰ",
                description_en="Caused by Tetranychus urticae. Tiny yellow stippling on leaves, fine webbing on underside. Explodes in hot dry weather. Source: ICAR-NCIPM & CIB&RC cibrc.nic.in.",
                description_hi="टेट्रेनाइकस यूर्टिके से। पत्तियों पर छोटे पीले धब्बे, नीचे जाले। गर्म शुष्क मौसम में तेजी से फैलता है। स्रोत: ICAR-NCIPM।",
                description_pa="ਟੈਟਰਾਨੀਕਸ ਯੂਰਟੀਕੇ ਕਾਰਨ। ਪੱਤਿਆਂ 'ਤੇ ਛੋਟੇ ਪੀਲੇ ਧੱਬੇ। ਸਰੋਤ: ICAR-NCIPM।",
                severity="high",
            ),
            Disease(
                id="tomato_yellow_leaf_curl",
                class_index=13,
                name_en="Yellow Leaf Curl Virus",
                name_hi="पीली पत्ती मरोड़ विषाणु",
                name_pa="ਪੀਲਾ ਪੱਤਾ ਕਰਲ ਵਾਇਰਸ",
                crop_en="Tomato",
                crop_hi="टमाटर",
                crop_pa="ਟਮਾਟਰ",
                description_en="Tomato Yellow Leaf Curl Virus (TYLCV) spread by whitefly Bemisia tabaci. Leaves curl upward, yellow, stunted plant. No cure — control vector. Source: ICAR-IIHR Bengaluru.",
                description_hi="TYLCV वायरस, सफेद मक्खी से फैलता है। पत्तियां ऊपर की ओर मुड़ती हैं, पीली होती हैं। इलाज नहीं, वेक्टर नियंत्रण करें। स्रोत: ICAR-IIHR।",
                description_pa="TYLCV ਵਾਇਰਸ, ਚਿੱਟੀ ਮੱਖੀ ਤੋਂ ਫੈਲਦਾ ਹੈ। ਪੱਤੇ ਉੱਪਰ ਵੱਲ ਮੁੜਦੇ ਹਨ। ਇਲਾਜ ਨਹੀਂ। ਸਰੋਤ: ICAR-IIHR।",
                severity="high",
            ),
            Disease(
                id="tomato_mosaic_virus",
                class_index=14,
                name_en="Tomato Mosaic Virus",
                name_hi="टमाटर मोजेक विषाणु",
                name_pa="ਟਮਾਟਰ ਮੋਜ਼ੇਕ ਵਾਇਰਸ",
                crop_en="Tomato",
                crop_hi="टमाटर",
                crop_pa="ਟਮਾਟਰ",
                description_en="Tobacco Mosaic Virus (TMV) — contact transmitted. Mottled yellow-green mosaic on leaves, distorted fruits. Rogue out infected plants immediately. Source: ICAR-IIHR Bengaluru.",
                description_hi="TMV वायरस, संपर्क से फैलता है। पत्तियों पर पीला-हरा मोजेक। संक्रमित पौधे तुरंत हटाएं। स्रोत: ICAR-IIHR।",
                description_pa="TMV ਵਾਇਰਸ, ਛੋਹ ਤੋਂ ਫੈਲਦਾ ਹੈ। ਸੰਕਰਮਿਤ ਪੌਦੇ ਤੁਰੰਤ ਹਟਾਓ। ਸਰੋਤ: ICAR-IIHR।",
                severity="high",
            ),
            Disease(
                id="tomato_bacterial_spot",
                class_index=15,
                name_en="Bacterial Spot",
                name_hi="बैक्टीरियल धब्बा",
                name_pa="ਬੈਕਟੀਰੀਅਲ ਧੱਬਾ",
                crop_en="Tomato",
                crop_hi="टमाटर",
                crop_pa="ਟਮਾਟਰ",
                description_en="Caused by Xanthomonas vesicatoria. Water-soaked dark spots on leaves and fruit. Spreads in warm wet conditions. Source: ICAR-IIHR Bengaluru.",
                description_hi="ज़ैंथोमोनस वेसीकेटोरिया से। पत्तियों और फल पर पानी भरे काले धब्बे। स्रोत: ICAR-IIHR।",
                description_pa="ਜ਼ੈਂਥੋਮੋਨਸ ਵੈਸੀਕੇਟੋਰੀਆ ਕਾਰਨ। ਪੱਤਿਆਂ ਅਤੇ ਫਲ 'ਤੇ ਧੱਬੇ। ਸਰੋਤ: ICAR-IIHR।",
                severity="medium",
            ),

            # ── POTATO ──
            Disease(
                id="potato_early_blight",
                class_index=16,
                name_en="Early Blight",
                name_hi="अगेती झुलसन",
                name_pa="ਅਗੇਤੀ ਝੁਲਸਣ",
                crop_en="Potato",
                crop_hi="आलू",
                crop_pa="ਆਲੂ",
                description_en="Caused by Alternaria solani. Concentric ring lesions on older leaves. Source: ICAR-CPRI Shimla (Central Potato Research Institute).",
                description_hi="अल्टरनेरिया सोलानी से। पुरानी पत्तियों पर छल्लेदार धब्बे। स्रोत: ICAR-CPRI शिमला।",
                description_pa="ਅਲਟਰਨੇਰੀਆ ਸੋਲਾਨੀ ਕਾਰਨ। ਪੁਰਾਣੇ ਪੱਤਿਆਂ 'ਤੇ ਛੱਲੇਦਾਰ ਧੱਬੇ। ਸਰੋਤ: ICAR-CPRI ਸ਼ਿਮਲਾ।",
                severity="medium",
            ),
            Disease(
                id="potato_late_blight",
                class_index=17,
                name_en="Late Blight",
                name_hi="पछेती झुलसन",
                name_pa="ਪਿਛੇਤੀ ਝੁਲਸਣ",
                crop_en="Potato",
                crop_hi="आलू",
                crop_pa="ਆਲੂ",
                description_en="Caused by Phytophthora infestans. Most devastating potato disease. Dark water-soaked lesions, white sporulation on leaf underside in humid conditions. Source: ICAR-CPRI Shimla.",
                description_hi="फाइटोफ्थोरा इन्फेस्टांस से। सबसे विनाशकारी आलू रोग। स्रोत: ICAR-CPRI शिमला।",
                description_pa="ਫਾਈਟੋਫਥੋਰਾ ਇਨਫੈਸਟਾਂਸ ਕਾਰਨ। ਸਭ ਤੋਂ ਵਿਨਾਸ਼ਕਾਰੀ ਆਲੂ ਰੋਗ। ਸਰੋਤ: ICAR-CPRI ਸ਼ਿਮਲਾ।",
                severity="high",
            ),

            # ── MAIZE ──
            Disease(
                id="maize_gray_leaf_spot",
                class_index=18,
                name_en="Gray Leaf Spot",
                name_hi="भूरा पत्ती धब्बा",
                name_pa="ਸਲੇਟੀ ਪੱਤਾ ਧੱਬਾ",
                crop_en="Maize",
                crop_hi="मक्का",
                crop_pa="ਮੱਕੀ",
                description_en="Caused by Cercospora zeae-maydis. Rectangular gray-tan lesions parallel to leaf veins. Source: ICAR-IIMR Ludhiana (Indian Institute of Maize Research).",
                description_hi="सर्कोस्पोरा ज़ी-मेडिस से। पत्ती की नसों के समानांतर भूरे आयताकार धब्बे। स्रोत: ICAR-IIMR लुधियाना।",
                description_pa="ਸਰਕੋਸਪੋਰਾ ਜ਼ੀ-ਮੇਡਿਸ ਕਾਰਨ। ਪੱਤੀ ਦੀਆਂ ਨਾੜੀਆਂ ਦੇ ਸਮਾਨਾਂਤਰ ਭੂਰੇ ਧੱਬੇ। ਸਰੋਤ: ICAR-IIMR ਲੁਧਿਆਣਾ।",
                severity="medium",
            ),
            Disease(
                id="maize_common_rust",
                class_index=19,
                name_en="Common Rust",
                name_hi="सामान्य रतुआ",
                name_pa="ਆਮ ਕੁੰਗੀ",
                crop_en="Maize",
                crop_hi="मक्का",
                crop_pa="ਮੱਕੀ",
                description_en="Caused by Puccinia sorghi. Brick-red pustules on both leaf surfaces. Use resistant hybrids HQPM-1, DHM-117. Source: ICAR-IIMR Ludhiana & PAU.",
                description_hi="पुक्सिनिया सोर्गी से। दोनों पत्ती सतहों पर ईंट-लाल फफोले। स्रोत: ICAR-IIMR।",
                description_pa="ਪੁਕਸੀਨੀਆ ਸੋਰਘੀ ਕਾਰਨ। ਦੋਵੇਂ ਪੱਤੀ ਸਤ੍ਹਾਂ 'ਤੇ ਇੱਟ-ਲਾਲ ਫੋੜੇ। ਸਰੋਤ: ICAR-IIMR।",
                severity="medium",
            ),
            Disease(
                id="maize_northern_leaf_blight",
                class_index=20,
                name_en="Northern Leaf Blight",
                name_hi="उत्तरी पत्ती झुलसन",
                name_pa="ਉੱਤਰੀ ਪੱਤਾ ਝੁਲਸਣ",
                crop_en="Maize",
                crop_hi="मक्का",
                crop_pa="ਮੱਕੀ",
                description_en="Caused by Exserohilum turcicum. Large cigar-shaped gray-green lesions. Can cause 50% yield loss. Source: ICAR-IIMR & NIPHM niphm.gov.in.",
                description_hi="एक्सेरोहाइलम टर्सिकम से। बड़े सिगार आकार के धूसर-हरे धब्बे। स्रोत: ICAR-IIMR।",
                description_pa="ਐਕਸੇਰੋਹਾਈਲਮ ਟਰਸੀਕਮ ਕਾਰਨ। ਵੱਡੇ ਸਿਗਾਰ ਆਕਾਰ ਦੇ ਧੱਬੇ। ਸਰੋਤ: ICAR-IIMR।",
                severity="high",
            ),
        ]

        db.add_all(diseases)
        db.commit()
        print(f"✓ Inserted {len(diseases)} diseases.")

        # ── TREATMENTS ──────────────────────────────────────────────
        treatments = [

            # WHEAT YELLOW RUST
            Treatment(disease_id="wheat_yellow_rust", type="organic",
                name_en="Sulphur 80% WP spray",
                name_hi="सल्फर 80% WP छिड़काव",
                name_pa="ਸਲਫਰ 80% WP ਛਿੜਕਾਅ",
                dosage="3g per litre of water",
                schedule="Spray at first yellow stripe · Repeat after 15 days · 500L water/acre"),
            Treatment(disease_id="wheat_yellow_rust", type="organic",
                name_en="Resistant varieties: HD 2967, PBW 621, WH 1105",
                name_hi="प्रतिरोधी किस्में: HD 2967, PBW 621, WH 1105",
                name_pa="ਰੋਧਕ ਕਿਸਮਾਂ: HD 2967, PBW 621, WH 1105",
                dosage="Use certified seed",
                schedule="Plant resistant variety next season · Source: PAU Ludhiana"),
            Treatment(disease_id="wheat_yellow_rust", type="chemical",
                name_en="Propiconazole 25% EC (Tilt — Syngenta)",
                name_hi="प्रोपिकोनाजोल 25% EC (टिल्ट — सिंजेंटा)",
                name_pa="ਪ੍ਰੋਪੀਕੋਨਾਜ਼ੋਲ 25% EC (ਟਿਲਟ — ਸਿੰਜੇਂਟਾ)",
                dosage="1ml per litre of water",
                schedule="Spray at first symptom · Repeat after 15 days if needed · PHI 21 days · ~₹380/acre · Source: ICAR-IIWBR Karnal"),
            Treatment(disease_id="wheat_yellow_rust", type="chemical",
                name_en="Tebuconazole 250 EC (Folicur — Bayer)",
                name_hi="टेबूकोनाजोल 250 EC (फोलिकर — बायर)",
                name_pa="ਟੇਬੂਕੋਨਾਜ਼ੋਲ 250 EC (ਫੋਲਿਕਰ — ਬਾਇਅਰ)",
                dosage="1ml per litre of water",
                schedule="Alternative to Propiconazole · PHI 21 days · 500L water/acre"),

            # WHEAT BROWN RUST
            Treatment(disease_id="wheat_brown_rust", type="organic",
                name_en="Sulphur dust 20–25 kg/acre",
                name_hi="सल्फर धूल 20-25 किग्रा/एकड़",
                name_pa="ਸਲਫਰ ਧੂੜ 20-25 ਕਿੱਲੋ/ਏਕੜ",
                dosage="20-25 kg per acre",
                schedule="Apply in early morning · Use resistant varieties PBW 550, HD 2781"),
            Treatment(disease_id="wheat_brown_rust", type="chemical",
                name_en="Propiconazole 25% EC (Tilt — Syngenta)",
                name_hi="प्रोपिकोनाजोल 25% EC",
                name_pa="ਪ੍ਰੋਪੀਕੋਨਾਜ਼ੋਲ 25% EC",
                dosage="1ml per litre of water",
                schedule="Spray at boot stage (flag leaf emergence) · One spray usually sufficient · PHI 21 days · Source: ICAR-IIWBR Karnal"),

            # WHEAT KARNAL BUNT
            Treatment(disease_id="wheat_karnal_bunt", type="organic",
                name_en="Carboxin 37.5% + Thiram 37.5% DS seed treatment",
                name_hi="कार्बोक्सिन + थीरम बीज उपचार",
                name_pa="ਕਾਰਬੋਕਸਿਨ + ਥੀਰਾਮ ਬੀਜ ਉਪਚਾਰ",
                dosage="3g per kg of seed",
                schedule="Treat seed BEFORE sowing · Use certified disease-free seed only · Report outbreak to state agriculture dept"),
            Treatment(disease_id="wheat_karnal_bunt", type="chemical",
                name_en="Tebuconazole 2% DS (Raxil — Bayer) seed treatment",
                name_hi="टेबूकोनाजोल 2% DS (रैक्सिल) बीज उपचार",
                name_pa="ਟੇਬੂਕੋਨਾਜ਼ੋਲ 2% DS (ਰੈਕਸਿਲ) ਬੀਜ ਉਪਚਾਰ",
                dosage="1.5g per kg of seed",
                schedule="Seed treatment mandatory · Foliar: Propiconazole 1ml/L at ear emergence · PHI 21 days · Source: ICAR-IIWBR Karnal"),

            # WHEAT POWDERY MILDEW
            Treatment(disease_id="wheat_powdery_mildew", type="organic",
                name_en="Sulphur 80% WP spray",
                name_hi="सल्फर 80% WP",
                name_pa="ਸਲਫਰ 80% WP",
                dosage="3g per litre of water",
                schedule="Very effective · Spray at first white patches · PHI 7 days"),
            Treatment(disease_id="wheat_powdery_mildew", type="chemical",
                name_en="Hexaconazole 5% SC (Contaf Plus — FMC)",
                name_hi="हेक्साकोनाजोल 5% SC (कॉन्टैफ प्लस)",
                name_pa="ਹੈਕਸਾਕੋਨਾਜ਼ੋਲ 5% SC (ਕੌਂਟੈਫ ਪਲੱਸ)",
                dosage="2ml per litre of water",
                schedule="Spray at first powdery patches · Repeat after 15 days · PHI 21 days · Source: PAU Ludhiana & HAU Hisar"),

            # RICE BLAST
            Treatment(disease_id="rice_blast", type="organic",
                name_en="Trichoderma viride seed treatment",
                name_hi="ट्राइकोडर्मा विराइड बीज उपचार",
                name_pa="ਟ੍ਰਾਈਕੋਡਰਮਾ ਵਿਰਾਈਡ ਬੀਜ ਉਪਚਾਰ",
                dosage="5g per kg of seed",
                schedule="Treat seed before sowing · Use blast-resistant varieties: IR64, Swarna, Pusa Basmati 1"),
            Treatment(disease_id="rice_blast", type="chemical",
                name_en="Azoxystrobin 23% SC (Amistar — Syngenta)",
                name_hi="एज़ोक्सीस्ट्रोबिन 23% SC (एमिस्टार)",
                name_pa="ਅਜ਼ੋਕਸੀਸਟ੍ਰੋਬਿਨ 23% SC (ਅਮਿਸਟਾਰ)",
                dosage="1ml per litre of water",
                schedule="Best option post-Tricyclazole ban · Spray at leaf blast onset · Second spray at panicle initiation · PHI 14 days · Source: ICAR-IIRR Hyderabad"),
            Treatment(disease_id="rice_blast", type="chemical",
                name_en="Azoxystrobin 11% + Tebuconazole 18.3% SC (Custodia)",
                name_hi="एज़ोक्सीस्ट्रोबिन + टेबूकोनाजोल SC (कस्टोडिया)",
                name_pa="ਅਜ਼ੋਕਸੀਸਟ੍ਰੋਬਿਨ + ਟੇਬੂਕੋਨਾਜ਼ੋਲ SC",
                dosage="1.5ml per litre of water",
                schedule="2 sprays at tillering and panicle initiation · PHI 14 days · ~₹400-600/acre"),

            # RICE SHEATH BLIGHT
            Treatment(disease_id="rice_sheath_blight", type="organic",
                name_en="Trichoderma harzianum soil application",
                name_hi="ट्राइकोडर्मा हर्जियानम मिट्टी में डालें",
                name_pa="ਟ੍ਰਾਈਕੋਡਰਮਾ ਹਾਰਜ਼ੀਅਨਮ ਮਿੱਟੀ ਵਿੱਚ",
                dosage="2.5 kg per acre mixed in FYM",
                schedule="Apply 7 days before transplanting · Reduce nitrogen fertilizer — excess promotes disease"),
            Treatment(disease_id="rice_sheath_blight", type="chemical",
                name_en="Azoxystrobin 11% + Tebuconazole 18.3% SC",
                name_hi="एज़ोक्सीस्ट्रोबिन + टेबूकोनाजोल SC",
                name_pa="ਅਜ਼ੋਕਸੀਸਟ੍ਰੋਬਿਨ + ਟੇਬੂਕੋਨਾਜ਼ੋਲ SC",
                dosage="750ml per acre",
                schedule="Most effective per ICAR-IIRR 10-centre trial · Spray at maximum tillering · Target stem base · PHI 14 days"),
            Treatment(disease_id="rice_sheath_blight", type="chemical",
                name_en="Hexaconazole 5% SC (Contaf — FMC)",
                name_hi="हेक्साकोनाजोल 5% SC (कॉन्टैफ)",
                name_pa="ਹੈਕਸਾਕੋਨਾਜ਼ੋਲ 5% SC (ਕੌਂਟੈਫ)",
                dosage="2ml per litre of water",
                schedule="Spray at maximum tillering stage · PHI 14 days · Source: ICAR-IIRR Hyderabad"),

            # RICE BLB
            Treatment(disease_id="rice_bacterial_leaf_blight", type="organic",
                name_en="Copper Oxychloride 50% WP (Blitox-50)",
                name_hi="कॉपर ऑक्सीक्लोराइड 50% WP (ब्लिटॉक्स-50)",
                name_pa="ਕਾਪਰ ਆਕਸੀਕਲੋਰਾਈਡ 50% WP",
                dosage="3g per litre of water",
                schedule="Use resistant varieties: IR-20, Pusa Basmati 1 · Drain fields during tillering"),
            Treatment(disease_id="rice_bacterial_leaf_blight", type="chemical",
                name_en="Streptomycin + Tetracycline (Agrimycin-100) + Copper Oxychloride",
                name_hi="स्ट्रेप्टोमाइसिन + टेट्रासाइक्लिन (एग्रीमाइसिन-100)",
                name_pa="ਸਟ੍ਰੈਪਟੋਮਾਈਸਿਨ + ਟੈਟਰਾਸਾਈਕਲਿਨ",
                dosage="100ppm Agrimycin + 3g/L Copper Oxychloride",
                schedule="2-3 sprays at 10-day intervals · PHI 5 days · Do not use Streptomycin more than 3× per season · Source: ICAR-NRRI Cuttack & niphm.gov.in"),

            # RICE BROWN SPOT
            Treatment(disease_id="rice_brown_spot", type="organic",
                name_en="Hot water seed treatment",
                name_hi="गर्म पानी बीज उपचार",
                name_pa="ਗਰਮ ਪਾਣੀ ਬੀਜ ਉਪਚਾਰ",
                dosage="52°C water for 10 minutes",
                schedule="Treat seed before sowing · Apply potassium fertilizer — deficiency worsens disease"),
            Treatment(disease_id="rice_brown_spot", type="chemical",
                name_en="Mancozeb 75% WP (Dithane M-45 / Indofil M-45)",
                name_hi="मैनकोजेब 75% WP (डाइथेन M-45)",
                name_pa="ਮੈਨਕੋਜ਼ੇਬ 75% WP (ਡਾਈਥੇਨ M-45)",
                dosage="2.5g per litre of water",
                schedule="2 sprays 10 days apart · PHI 21 days · Source: ICAR-NRRI Cuttack"),

            # TOMATO EARLY BLIGHT
            Treatment(disease_id="tomato_early_blight", type="organic",
                name_en="Copper Oxychloride 50% WP (Blitox)",
                name_hi="कॉपर ऑक्सीक्लोराइड 50% WP (ब्लिटॉक्स)",
                name_pa="ਕਾਪਰ ਆਕਸੀਕਲੋਰਾਈਡ 50% WP",
                dosage="3g per litre of water",
                schedule="Preventive spray · Start at transplanting"),
            Treatment(disease_id="tomato_early_blight", type="chemical",
                name_en="Mancozeb 75% WP (Dithane M-45)",
                name_hi="मैनकोजेब 75% WP (डाइथेन M-45)",
                name_pa="ਮੈਨਕੋਜ਼ੇਬ 75% WP",
                dosage="2g per litre of water",
                schedule="3-4 sprays at 10-day intervals · PHI 7 days · Rotate fungicide groups · Source: ICAR-IIHR Bengaluru & NCIPM"),
            Treatment(disease_id="tomato_early_blight", type="chemical",
                name_en="Chlorothalonil 75% WP (Kavach — UPL)",
                name_hi="क्लोरोथालोनिल 75% WP (कवच — UPL)",
                name_pa="ਕਲੋਰੋਥਾਲੋਨਿਲ 75% WP (ਕਵਚ)",
                dosage="2g per litre of water",
                schedule="Alternative to Mancozeb · PHI 7 days · ~₹300-500/acre"),

            # TOMATO LATE BLIGHT
            Treatment(disease_id="tomato_late_blight", type="organic",
                name_en="Copper Oxychloride 50% WP — preventive spray",
                name_hi="कॉपर ऑक्सीक्लोराइड — निवारक छिड़काव",
                name_pa="ਕਾਪਰ ਆਕਸੀਕਲੋਰਾਈਡ — ਰੋਕਥਾਮ ਛਿੜਕਾਅ",
                dosage="3g per litre of water",
                schedule="Apply BEFORE disease appears during monsoon · Remove infected leaves — do not compost"),
            Treatment(disease_id="tomato_late_blight", type="chemical",
                name_en="Metalaxyl 8% + Mancozeb 64% WP (Ridomil Gold MZ)",
                name_hi="मेटालैक्सिल + मैनकोजेब (रिडोमिल गोल्ड MZ)",
                name_pa="ਮੈਟਾਲੈਕਸਿਲ + ਮੈਨਕੋਜ਼ੇਬ (ਰਿਡੋਮਿਲ ਗੋਲਡ MZ)",
                dosage="2.5g per litre of water",
                schedule="Preventive spray in monsoon · Every 5-7 days · PHI 3-5 days · Critical: act at first sign · Source: ICAR-IIHR Bengaluru & niphm.gov.in"),
            Treatment(disease_id="tomato_late_blight", type="chemical",
                name_en="Dimethomorph 50% WP (Acrobat — BASF)",
                name_hi="डाइमेथोमॉर्फ 50% WP (एक्रोबेट)",
                name_pa="ਡਾਈਮੇਥੋਮੋਰਫ 50% WP (ਐਕਰੋਬੈਟ)",
                dosage="1g per litre of water",
                schedule="Rotate with Ridomil · PHI 5 days · ~₹600-900/acre"),

            # TOMATO SPIDER MITES
            Treatment(disease_id="tomato_spider_mites", type="organic",
                name_en="Neem oil spray on leaf underside",
                name_hi="नीम तेल पत्ती के नीचे छिड़काव",
                name_pa="ਨਿੰਮ ਦਾ ਤੇਲ ਪੱਤੇ ਦੇ ਹੇਠਾਂ ਛਿੜਕਾਅ",
                dosage="5ml neem oil + 2ml soap per litre",
                schedule="Spray on UNDERSIDE of leaves — critical · Sulphur 80% WP @ 3g/L also effective"),
            Treatment(disease_id="tomato_spider_mites", type="chemical",
                name_en="Abamectin 1.9% EC (Vertimec — Syngenta)",
                name_hi="अबामेक्टिन 1.9% EC (वर्टिमेक — सिंजेंटा)",
                name_pa="ਅਬਾਮੈਕਟਿਨ 1.9% EC (ਵਰਟੀਮੇਕ)",
                dosage="1ml per litre of water",
                schedule="Spray on UNDERSIDE of leaves · 2 sprays at 7-day interval · Rotate miticide groups · PHI 3 days · Source: ICAR-NCIPM & cibrc.nic.in"),

            # TOMATO YELLOW LEAF CURL
            Treatment(disease_id="tomato_yellow_leaf_curl", type="organic",
                name_en="Yellow sticky traps + resistant varieties",
                name_hi="पीले चिपचिपे जाल + प्रतिरोधी किस्में",
                name_pa="ਪੀਲੇ ਚਿਪਕਣ ਵਾਲੇ ਜਾਲ + ਰੋਧਕ ਕਿਸਮਾਂ",
                dosage="10 traps per acre",
                schedule="Monitor whitefly population · Use virus-resistant varieties: Arka Rakshak, US-440 · Rogue out infected plants immediately"),
            Treatment(disease_id="tomato_yellow_leaf_curl", type="chemical",
                name_en="Imidacloprid 17.8% SL (Confidor — Bayer) for whitefly",
                name_hi="इमिडाक्लोप्रिड 17.8% SL (कॉन्फिडोर) सफेद मक्खी के लिए",
                name_pa="ਇਮੀਡਾਕਲੋਪ੍ਰਿਡ 17.8% SL (ਕੌਨਫਿਡੋਰ)",
                dosage="0.5ml per litre of water",
                schedule="No cure for virus — control whitefly vector · Begin at transplanting · Every 10 days · PHI 3 days · Source: ICAR-IIHR Bengaluru"),

            # TOMATO MOSAIC VIRUS
            Treatment(disease_id="tomato_mosaic_virus", type="organic",
                name_en="Sanitation — remove and burn infected plants",
                name_hi="सफाई — संक्रमित पौधे हटाएं और जलाएं",
                name_pa="ਸਫਾਈ — ਸੰਕਰਮਿਤ ਪੌਦੇ ਹਟਾਓ ਅਤੇ ਸਾੜੋ",
                dosage="No chemical cure for virus",
                schedule="Remove infected plants within 48 hours · Wash hands and tools with soap · Sanitize tools with 1% sodium hypochlorite · Use resistant varieties: Pusa Ruby, Pusa Gaurav"),
            Treatment(disease_id="tomato_mosaic_virus", type="chemical",
                name_en="Imidacloprid 17.8% SL for aphid vector control",
                name_hi="इमिडाक्लोप्रिड — माहू वेक्टर नियंत्रण",
                name_pa="ਇਮੀਡਾਕਲੋਪ੍ਰਿਡ — ਮਾਹੂ ਵੈਕਟਰ ਕੰਟਰੋਲ",
                dosage="0.5ml per litre of water",
                schedule="Control aphid vectors · PHI 3 days · Source: ICAR-IIHR Bengaluru"),

            # TOMATO BACTERIAL SPOT
            Treatment(disease_id="tomato_bacterial_spot", type="organic",
                name_en="Copper Oxychloride 50% WP (Blitox-50)",
                name_hi="कॉपर ऑक्सीक्लोराइड (ब्लिटॉक्स-50)",
                name_pa="ਕਾਪਰ ਆਕਸੀਕਲੋਰਾਈਡ (ਬਲਿਟੋਕਸ-50)",
                dosage="3g per litre of water",
                schedule="Avoid overhead irrigation — use drip · Spray at 10-12 day intervals"),
            Treatment(disease_id="tomato_bacterial_spot", type="chemical",
                name_en="Streptomycin + Tetracycline (Agrimycin-100)",
                name_hi="स्ट्रेप्टोमाइसिन + टेट्रासाइक्लिन (एग्रीमाइसिन-100)",
                name_pa="ਸਟ੍ਰੈਪਟੋਮਾਈਸਿਨ + ਟੈਟਰਾਸਾਈਕਲਿਨ",
                dosage="100ppm solution",
                schedule="Begin at transplanting · 10-12 day intervals · PHI 5 days · Max 3 applications/season · Source: ICAR-IIHR Bengaluru"),

            # POTATO EARLY BLIGHT
            Treatment(disease_id="potato_early_blight", type="organic",
                name_en="Copper Oxychloride 50% WP (Blitox)",
                name_hi="कॉपर ऑक्सीक्लोराइड (ब्लिटॉक्स)",
                name_pa="ਕਾਪਰ ਆਕਸੀਕਲੋਰਾਈਡ",
                dosage="3g per litre of water",
                schedule="Preventive spray · Trichoderma viride @ 5g/kg seed treatment"),
            Treatment(disease_id="potato_early_blight", type="chemical",
                name_en="Mancozeb 75% WP (Dithane M-45 / Indofil M-45)",
                name_hi="मैनकोजेब 75% WP (डाइथेन M-45)",
                name_pa="ਮੈਨਕੋਜ਼ੇਬ 75% WP",
                dosage="2g per litre of water",
                schedule="3-4 sprays at 10-day intervals · PHI 7 days · Source: ICAR-CPRI Shimla"),

            # POTATO LATE BLIGHT
            Treatment(disease_id="potato_late_blight", type="organic",
                name_en="Copper Oxychloride 50% WP — begin before disease",
                name_hi="कॉपर ऑक्सीक्लोराइड — रोग से पहले शुरू करें",
                name_pa="ਕਾਪਰ ਆਕਸੀਕਲੋਰਾਈਡ — ਬਿਮਾਰੀ ਤੋਂ ਪਹਿਲਾਂ ਸ਼ੁਰੂ ਕਰੋ",
                dosage="3g per litre of water",
                schedule="Apply before disease appears · Remove and burn infected haulms"),
            Treatment(disease_id="potato_late_blight", type="chemical",
                name_en="Metalaxyl 8% + Mancozeb 64% WP (Ridomil Gold)",
                name_hi="मेटालैक्सिल + मैनकोजेब (रिडोमिल गोल्ड)",
                name_pa="ਮੈਟਾਲੈਕਸਿਲ + ਮੈਨਕੋਜ਼ੇਬ (ਰਿਡੋਮਿਲ ਗੋਲਡ)",
                dosage="2.5g per litre of water",
                schedule="Spray every 7 days in cool humid weather · PHI 7 days · ~₹500-800/acre · Source: ICAR-CPRI Shimla"),
            Treatment(disease_id="potato_late_blight", type="chemical",
                name_en="Cymoxanil 8% + Mancozeb 64% WP (Curzate M8)",
                name_hi="साइमोक्सानिल + मैनकोजेब (कर्जेट M8)",
                name_pa="ਸਾਈਮੋਕਸਾਨਿਲ + ਮੈਨਕੋਜ਼ੇਬ (ਕਰਜ਼ੇਟ M8)",
                dosage="2.5g per litre of water",
                schedule="Rotate with Ridomil · PHI 7 days"),

            # MAIZE GRAY LEAF SPOT
            Treatment(disease_id="maize_gray_leaf_spot", type="organic",
                name_en="Trichoderma viride seed treatment",
                name_hi="ट्राइकोडर्मा विराइड बीज उपचार",
                name_pa="ਟ੍ਰਾਈਕੋਡਰਮਾ ਵਿਰਾਈਡ ਬੀਜ ਉਪਚਾਰ",
                dosage="5g per kg of seed",
                schedule="Treat before sowing · Neem cake @ 250kg/acre in soil"),
            Treatment(disease_id="maize_gray_leaf_spot", type="chemical",
                name_en="Mancozeb 75% WP (Dithane M-45)",
                name_hi="मैनकोजेब 75% WP",
                name_pa="ਮੈਨਕੋਜ਼ੇਬ 75% WP",
                dosage="2g per litre of water",
                schedule="First spray at 40-45 DAS · Second spray 15 days later · 500L water/acre · PHI 21 days · Source: ICAR-IIMR Ludhiana"),

            # MAIZE COMMON RUST
            Treatment(disease_id="maize_common_rust", type="organic",
                name_en="Sulphur 80% WP + resistant hybrids",
                name_hi="सल्फर 80% WP + प्रतिरोधी संकर",
                name_pa="ਸਲਫਰ 80% WP + ਰੋਧਕ ਹਾਈਬ੍ਰਿਡ",
                dosage="3g per litre of water",
                schedule="Use resistant hybrid varieties: HQPM-1, DHM-117 · Source: ICAR-IIMR & PAU"),
            Treatment(disease_id="maize_common_rust", type="chemical",
                name_en="Propiconazole 25% EC",
                name_hi="प्रोपिकोनाजोल 25% EC",
                name_pa="ਪ੍ਰੋਪੀਕੋਨਾਜ਼ੋਲ 25% EC",
                dosage="1ml per litre of water",
                schedule="Spray at first pustule appearance · Repeat after 10-12 days · PHI 21 days"),

            # MAIZE NORTHERN LEAF BLIGHT
            Treatment(disease_id="maize_northern_leaf_blight", type="organic",
                name_en="Trichoderma harzianum seed treatment",
                name_hi="ट्राइकोडर्मा हर्जियानम बीज उपचार",
                name_pa="ਟ੍ਰਾਈਕੋਡਰਮਾ ਹਾਰਜ਼ੀਅਨਮ ਬੀਜ ਉਪਚਾਰ",
                dosage="5g per kg of seed",
                schedule="Treat before sowing · Bacillus subtilis @ 2g/L foliar spray · Improve drainage"),
            Treatment(disease_id="maize_northern_leaf_blight", type="chemical",
                name_en="Azoxystrobin 23% SC (Amistar — Syngenta)",
                name_hi="एज़ोक्सीस्ट्रोबिन 23% SC (एमिस्टार)",
                name_pa="ਅਜ਼ੋਕਸੀਸਟ੍ਰੋਬਿਨ 23% SC (ਅਮਿਸਟਾਰ)",
                dosage="1ml per litre of water",
                schedule="Spray at VT stage (tasseling) · Repeat at 10-day interval × 2 sprays · PHI 21 days · Source: ICAR-IIMR & niphm.gov.in"),
        ]

        db.add_all(treatments)
        db.commit()
        print(f"✓ Inserted {len(treatments)} treatments.")
        print("\n✅ Database seeded successfully!")
        print("Sources: ICAR-NCIPM, NIPHM, ICAR-IIWBR Karnal, ICAR-IIRR Hyderabad,")
        print("         ICAR-IIHR Bengaluru, ICAR-CPRI Shimla, ICAR-IIMR Ludhiana,")
        print("         PAU Ludhiana, HAU Hisar, CIB&RC (cibrc.nic.in)")

    except Exception as e:
        db.rollback()
        print(f"❌ Error: {e}")
        raise
    finally:
        db.close()

if __name__ == "__main__":
    seed()